#!/usr/bin/env bash

set -eu

flags=(
    "-ferror-limit=1"
    "-fno-autolink"
    "-fno-exceptions"
    "-fno-math-errno"
    "-fno-omit-frame-pointer"
    "-fno-rtti"
    "-fno-unwind-tables"
    "-fsanitize=address"
    "-fsanitize=undefined"
    "-fshort-enums"
    "-fuse-ld=lld"
    "-march=native"
    "-O1"
    "-std=c++11"
    "-Werror"
    "-Weverything"
    "-Wno-extra-semi-stmt"
    "-Wno-reserved-id-macro"
)

now () {
    date +%s.%N
}

(
    start=$(now)
    clang-format -i -verbose "$WD/src"/*
    clang++ "${flags[@]}" -o "$WD/bin/main" "$WD/src/main.cpp"
    end=$(now)
    python3 -c "print(\"Compiled! ({:.3f}s)\n\".format($end - $start))"
)

time "$WD/bin/main" "$WD/out/melody.ly"
