#!/usr/bin/env bash

set -eu

flags=(
    -ccopt "-static"
    -nolabels
    -strict-formats
    -strict-sequence
    -unboxed-types
    -w "+1..67-40-42"
)

ocp-indent -i "$WD/src/"*.ml
cp "$WD/src/"*.ml "$WD/build/"

(
    cd "$WD/build/"
    ocamlc "${flags[@]}" "main.ml" -o "$WD/bin/main"
    "$WD/bin/main" "$WD/out/melody.ly"
)
